/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.presentation;

import edu.esprit.dao.JoueurDAO;
import edu.esprit.entite.Joueur;
//import static edu.esprit.presentation.AjouterJoueur.e;
import javax.swing.JOptionPane;

/**
 *
 * @author Wael Mallek
 */
public class AfficherJoueur extends javax.swing.JFrame {

    static Joueur e;
    /**
     * Creates new form AfficherEmployeJoueur
     */
    public AfficherJoueur() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeJoueur = new javax.swing.JTable();
        Modifiericon = new javax.swing.JLabel();
        supprimericon = new javax.swing.JLabel();
        Retouricon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 700));
        setMinimumSize(new java.awt.Dimension(1366, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Liste Joueurs");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 81, 15);

        ListeJoueur.setBackground(new java.awt.Color(0, 204, 51));
        ListeJoueur.setModel(new edu.esprit.presentation.JoueurTableModel());
        jScrollPane1.setViewportView(ListeJoueur);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 1330, 330);

        Modifiericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/modifier.png"))); // NOI18N
        Modifiericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifiericonMouseClicked(evt);
            }
        });
        getContentPane().add(Modifiericon);
        Modifiericon.setBounds(1010, 580, 160, 50);

        supprimericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/supprimer.png"))); // NOI18N
        supprimericon.setText("jLabel11");
        supprimericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimericonMouseClicked(evt);
            }
        });
        getContentPane().add(supprimericon);
        supprimericon.setBounds(1180, 580, 160, 50);

        Retouricon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/precident.png"))); // NOI18N
        Retouricon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetouriconMouseClicked(evt);
            }
        });
        getContentPane().add(Retouricon);
        Retouricon.setBounds(10, 580, 160, 45);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouterJoueur.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       // entreprise_name.setText(e.getLibelle_entreprise());
    }//GEN-LAST:event_formWindowOpened

    private void supprimericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimericonMouseClicked
        // TODO add your handling code here:
        int id = Integer.parseInt(ListeJoueur.getValueAt(ListeJoueur.getSelectedRow(),0).toString());
        int id_equipe=Integer.parseInt(ListeJoueur.getValueAt(ListeJoueur.getSelectedRow(),1).toString());
        String Nom=ListeJoueur.getValueAt(ListeJoueur.getSelectedRow(),2).toString();
        String Prenom=ListeJoueur.getValueAt(ListeJoueur.getSelectedRow(),3).toString();
        String Saison=ListeJoueur.getValueAt(ListeJoueur.getSelectedRow(),4).toString();
        int Num=Integer.parseInt(ListeJoueur.getValueAt(ListeJoueur.getSelectedRow(),5).toString());
        Joueur e=new Joueur(id,id_equipe,Num,Nom,Prenom,Saison);
        JoueurDAO employeDAO = new JoueurDAO();
        
        if(employeDAO.deleteJoueur(e)){
            JOptionPane.showMessageDialog(this, "Supprission effectué avec succès !");
            ListeJoueur.setModel(new edu.esprit.presentation.JoueurTableModel());

        }
    }//GEN-LAST:event_supprimericonMouseClicked

    private void ModifiericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifiericonMouseClicked
        // TODO add your handling code here:
         int id = Integer.parseInt(ListeJoueur.getValueAt(ListeJoueur.getSelectedRow(),0).toString());
        int id_equipe=Integer.parseInt(ListeJoueur.getValueAt(ListeJoueur.getSelectedRow(),1).toString());
        String Nom=ListeJoueur.getValueAt(ListeJoueur.getSelectedRow(),2).toString();
        String Prenom=ListeJoueur.getValueAt(ListeJoueur.getSelectedRow(),3).toString();
        String Saison=ListeJoueur.getValueAt(ListeJoueur.getSelectedRow(),4).toString();
        int Num=Integer.parseInt(ListeJoueur.getValueAt(ListeJoueur.getSelectedRow(),5).toString());
        Joueur e=new Joueur(id,id_equipe,Num,Nom,Prenom,Saison);
        this.setVisible(false);
        new AjouterJoueur(e).setVisible(true);
    }//GEN-LAST:event_ModifiericonMouseClicked

    private void RetouriconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetouriconMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_RetouriconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfficherJoueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfficherJoueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfficherJoueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfficherJoueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfficherJoueur().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListeJoueur;
    private javax.swing.JLabel Modifiericon;
    private javax.swing.JLabel Retouricon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel supprimericon;
    // End of variables declaration//GEN-END:variables
}
