/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.presentation;

import edu.esprit.dao.UtilisateurDAO;
import edu.esprit.entite.Utilisateur;
//import static edu.esprit.presentation.AjouterUtilisateur.e;
import javax.swing.JOptionPane;

/**
 *
 * @author Wael Mallek
 */
public class AfficherUtilisateur extends javax.swing.JFrame {

    static Utilisateur e;
    /**
     * Creates new form AfficherEmployeUtilisateur
     */
    public AfficherUtilisateur() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeUtilisateur = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        bntModifier = new javax.swing.JButton();
        Btnsupprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Liste Utilisateurs");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 101, 15);

        ListeUtilisateur.setModel(new edu.esprit.presentation.UtilisateurTableModel());
        jScrollPane1.setViewportView(ListeUtilisateur);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(14, 156, 609, 191);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Retour.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 365, 121, 37);

        bntModifier.setText("Modifier");
        bntModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntModifierActionPerformed(evt);
            }
        });
        getContentPane().add(bntModifier);
        bntModifier.setBounds(531, 115, 71, 23);

        Btnsupprimer.setText("Supprimer");
        Btnsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(Btnsupprimer);
        Btnsupprimer.setBounds(440, 115, 81, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DashboardAdmin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       // entreprise_name.setText(e.getLibelle_entreprise());
    }//GEN-LAST:event_formWindowOpened

    private void bntModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntModifierActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),0).toString());
        String Nom=ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),1).toString();
        String Prenom=ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),2).toString();
        String Role=ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),3).toString();
        String mail=ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),4).toString();
        String Tel =ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),5).toString();
        String Login =ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),6).toString();
        String Mopasse=ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),7).toString();
        Utilisateur user=new Utilisateur(id,Nom,Prenom,Role,mail,Tel,Login,Mopasse);
        this.setVisible(false);
        new AjouterUtilisateur(user).setVisible(true);
    }//GEN-LAST:event_bntModifierActionPerformed

    private void BtnsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsupprimerActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),0).toString());
        String Nom=ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),1).toString();
        String Prenom=ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),2).toString();
        String Role=ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),3).toString();
        String mail=ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),4).toString();
        String Tel =ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),5).toString();
        String Login =ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),6).toString();
        String Mopasse=ListeUtilisateur.getValueAt(ListeUtilisateur.getSelectedRow(),7).toString();
        Utilisateur user=new Utilisateur(id,Nom,Prenom,Role,mail,Tel,Login,Mopasse);
        UtilisateurDAO employeDAO = new UtilisateurDAO();
        
        if(employeDAO.deleteUtilisateur(user)){
            JOptionPane.showMessageDialog(this, "Supprission effectué avec succès !");
            ListeUtilisateur.setModel(new edu.esprit.presentation.UtilisateurTableModel());

        }
        
    }//GEN-LAST:event_BtnsupprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfficherUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfficherUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfficherUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfficherUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfficherUtilisateur().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnsupprimer;
    private javax.swing.JTable ListeUtilisateur;
    private javax.swing.JButton bntModifier;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
