/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.presentation;

import edu.esprit.dao.EquipeDAO;
import edu.esprit.entite.Equipe;
import static edu.esprit.presentation.AjouterEquipe.e;
import javax.swing.JOptionPane;

/**
 *
 * @author Wael Mallek
 */
public class AfficherEquipe extends javax.swing.JFrame {

    static Equipe e;
    /**
     * Creates new form AfficherEmployeEquipe
     */
    public AfficherEquipe() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListeEquipe = new javax.swing.JTable();
        supprimericon = new javax.swing.JLabel();
        Modifiericon = new javax.swing.JLabel();
        Retouricon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 700));
        setPreferredSize(new java.awt.Dimension(1366, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        ListeEquipe.setModel(new edu.esprit.presentation.EquipeTableModel());
        jScrollPane1.setViewportView(ListeEquipe);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 241, 1310, 310);

        supprimericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/supprimer.png"))); // NOI18N
        supprimericon.setText("jLabel11");
        supprimericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimericonMouseClicked(evt);
            }
        });
        getContentPane().add(supprimericon);
        supprimericon.setBounds(1180, 580, 160, 50);

        Modifiericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/modifier.png"))); // NOI18N
        Modifiericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifiericonMouseClicked(evt);
            }
        });
        getContentPane().add(Modifiericon);
        Modifiericon.setBounds(1010, 580, 160, 50);

        Retouricon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/precident.png"))); // NOI18N
        Retouricon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetouriconMouseClicked(evt);
            }
        });
        getContentPane().add(Retouricon);
        Retouricon.setBounds(10, 580, 160, 45);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/listeequipe.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       // entreprise_name.setText(e.getLibelle_entreprise());
    }//GEN-LAST:event_formWindowOpened

    private void supprimericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimericonMouseClicked
        // TODO add your handling code here:
        int id = Integer.parseInt(ListeEquipe.getValueAt(ListeEquipe.getSelectedRow(),0).toString());
        String nom=ListeEquipe.getValueAt(ListeEquipe.getSelectedRow(),1).toString();
        String Entrenaire=ListeEquipe.getValueAt(ListeEquipe.getSelectedRow(),2).toString();
        String Flux=ListeEquipe.getValueAt(ListeEquipe.getSelectedRow(),3).toString();
        Equipe equipe=new Equipe(id, nom, Entrenaire,Flux);
        EquipeDAO employeDAO = new EquipeDAO();
        
        if(employeDAO.deleteEquipe(equipe)){
            JOptionPane.showMessageDialog(this, "Supprission effectué avec succès !");
            ListeEquipe.setModel(new edu.esprit.presentation.EquipeTableModel());

        }
        
    }//GEN-LAST:event_supprimericonMouseClicked

    private void ModifiericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifiericonMouseClicked
        // TODO add your handling code here:
        int id = Integer.parseInt(ListeEquipe.getValueAt(ListeEquipe.getSelectedRow(),0).toString());
        String nom=ListeEquipe.getValueAt(ListeEquipe.getSelectedRow(),1).toString();
        String Entrenaire=ListeEquipe.getValueAt(ListeEquipe.getSelectedRow(),2).toString();
        String Flux=ListeEquipe.getValueAt(ListeEquipe.getSelectedRow(),3).toString();
        Equipe e=new Equipe(id, nom, Entrenaire,Flux);
        this.setVisible(false);
        new AjouterEquipe(e).setVisible(true);
    }//GEN-LAST:event_ModifiericonMouseClicked

    private void RetouriconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetouriconMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_RetouriconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfficherEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfficherEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfficherEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfficherEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfficherEquipe().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListeEquipe;
    private javax.swing.JLabel Modifiericon;
    private javax.swing.JLabel Retouricon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel supprimericon;
    // End of variables declaration//GEN-END:variables
}
