/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.presentation;

import edu.esprit.dao.EquipeDAO;

import edu.esprit.entite.Equipe;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Wael Mallek
 */
public class AjouterEquipe extends javax.swing.JFrame {
static Equipe e=null;
    
    /**
     * Creates new form AjouterEquipe
     */
    public AjouterEquipe() {
        initComponents();
    }
    public AjouterEquipe(Equipe e) {
        initComponents();
        this.e=e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom_Field = new javax.swing.JTextField();
        entraineur_Field = new javax.swing.JTextField();
        valider_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Flux_text = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Ajouter une equipe :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 99, 14);

        jLabel2.setText("Nom:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(84, 64, 25, 14);

        jLabel3.setText("entraineur:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(55, 106, 54, 14);
        getContentPane().add(nom_Field);
        nom_Field.setBounds(119, 61, 206, 20);
        getContentPane().add(entraineur_Field);
        entraineur_Field.setBounds(119, 103, 206, 20);

        valider_button.setText("Valider");
        valider_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valider_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(valider_button);
        valider_button.setBounds(260, 223, 65, 23);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Retour.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 264, 121, 37);

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifier);
        btnModifier.setBounds(183, 223, 71, 23);

        jLabel4.setText("Flux :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(82, 137, 27, 14);
        getContentPane().add(Flux_text);
        Flux_text.setBounds(119, 134, 206, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DashboardAdmin().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (e!=null) {
            nom_Field.setText(e.getNom());
            entraineur_Field.setText(e.getEntraineur());
            Flux_text.setText(e.getFlux());
            valider_button.setVisible(false);
            btnModifier.setVisible(true);
        }else
        {
            valider_button.setVisible(true);
            btnModifier.setVisible(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void valider_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valider_buttonActionPerformed
        // TODO add your handling code here:
        
        Equipe equipe = new Equipe(nom_Field.getText(), entraineur_Field.getText(),Flux_text.getText());
        EquipeDAO employeDAO = new EquipeDAO();
        if(employeDAO.addEquipe(equipe) != 0){
            JOptionPane.showMessageDialog(this, "Ajout effectué avec succès !");
        }
    }//GEN-LAST:event_valider_buttonActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        Equipe equipe = new Equipe(e.getId(),nom_Field.getText(), entraineur_Field.getText(),Flux_text.getText());
        EquipeDAO employeDAO = new EquipeDAO();
        if(employeDAO.updateEquipe(equipe)){
            JOptionPane.showMessageDialog(this, "Modification effectué avec succès !");
            this.setVisible(false);
            new AfficherEquipe().setVisible(true);
        }
    }//GEN-LAST:event_btnModifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterEquipe().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Flux_text;
    private javax.swing.JButton btnModifier;
    private javax.swing.JTextField entraineur_Field;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nom_Field;
    private javax.swing.JButton valider_button;
    // End of variables declaration//GEN-END:variables
}
