/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.presentation;

import edu.esprit.dao.FavoritsDAO;
import edu.esprit.dao.FavoritsDAO;
import edu.esprit.entite.Favorits;
import edu.esprit.entite.Favorits;
import static edu.esprit.presentation.AjouterFavorits.e;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Wael Mallek
 */
public class AjouterFavorits extends javax.swing.JFrame {
    static Favorits e=null;
    FavoritsDAO equipeDAO = new FavoritsDAO();
    ArrayList<Favorits> equipes = equipeDAO.readAllFavoritss();
    /**
     * Creates new form AjouterFavorits
     */
    public AjouterFavorits() {
        initComponents();
    }
    public AjouterFavorits(Favorits e) {
        initComponents();
        this.e=e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_Utilisateur_Field = new javax.swing.JTextField();
        id_equipe = new javax.swing.JComboBox();
        validericon = new javax.swing.JLabel();
        Modifiericon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 700));
        setPreferredSize(new java.awt.Dimension(1366, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id uilisateur:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 180, 60, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Equipe :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 220, 39, 14);
        getContentPane().add(id_Utilisateur_Field);
        id_Utilisateur_Field.setBounds(560, 170, 190, 30);

        id_equipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_equipeActionPerformed(evt);
            }
        });
        getContentPane().add(id_equipe);
        id_equipe.setBounds(560, 220, 190, 30);

        validericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/valider.png"))); // NOI18N
        validericon.setText("jLabel11");
        validericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validericonMouseClicked(evt);
            }
        });
        getContentPane().add(validericon);
        validericon.setBounds(560, 410, 160, 50);

        Modifiericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/modifier.png"))); // NOI18N
        Modifiericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifiericonMouseClicked(evt);
            }
        });
        getContentPane().add(Modifiericon);
        Modifiericon.setBounds(560, 410, 160, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AJOUTERFAVORIT.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if(e.getId()==0)
            {
                id_Utilisateur_Field.setText(Integer.toString(e.getId_User()));
            
            validericon.setVisible(true);
            Modifiericon.setVisible(false);
            }else
        if (e!=null) {
            id_Utilisateur_Field.setText(Integer.toString(e.getId_User()));
            
            validericon.setVisible(false);
            Modifiericon.setVisible(true);
        }else
            
        {
            validericon.setVisible(true);
            Modifiericon.setVisible(false);
            
        }
        for (int i = 0; i < equipes.size(); i++) {
            id_equipe.addItem(equipes.get(i).getId());
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void id_equipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_equipeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_id_equipeActionPerformed

    private void validericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validericonMouseClicked
        // TODO add your handling code here:
        Favorits equipe = equipes.get(id_equipe.getSelectedIndex()); //Récuperer l'equipe séléctionnée à partir du ComboBox 
        Favorits favorits = new Favorits(Integer.parseInt(id_Utilisateur_Field.getText()), equipe.getId());
        FavoritsDAO favoritsDAO = new FavoritsDAO();
        if(favoritsDAO.addFavorits(favorits) != 0){
            JOptionPane.showMessageDialog(this, "Ajout effectué avec succès !");
            this.setVisible(false);
        }
    }//GEN-LAST:event_validericonMouseClicked

    private void ModifiericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifiericonMouseClicked
        // TODO add your handling code here:
       Favorits equipe = new Favorits(e.getId(), e.getId_User(), e.getId_equipe());
        FavoritsDAO employeDAO = new FavoritsDAO();
        if(employeDAO.updateFavorits(equipe)){
            JOptionPane.showMessageDialog(this, "Modification effectué avec succès !");
            this.setVisible(false);
            new AfficherFavorits().setVisible(true);
        }
    }//GEN-LAST:event_ModifiericonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterFavorits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterFavorits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterFavorits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterFavorits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterFavorits().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Modifiericon;
    private javax.swing.JTextField id_Utilisateur_Field;
    private javax.swing.JComboBox id_equipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel validericon;
    // End of variables declaration//GEN-END:variables
}
