/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.presentation;


import edu.esprit.dao.UtilisateurDAO;
import edu.esprit.entite.Utilisateur;
import static edu.esprit.presentation.AjouterEquipe.e;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Wael Mallek
 */
public class AjouterUtilisateur extends javax.swing.JFrame {
 static Utilisateur user=null;
    
    /**
     * Creates new form AjouterUtilisateur
     */
    public AjouterUtilisateur() {
        initComponents();
    }

    AjouterUtilisateur(Utilisateur e) {
        initComponents();
        user=e;
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom_Field = new javax.swing.JTextField();
        prenom_Field = new javax.swing.JTextField();
        valider_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Role_Field = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        Email_Field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tel_Field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        login_Field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Password_Field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnModifier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Ajouter un Utilisateur :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 109, 14);

        jLabel2.setText("Nom:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(94, 64, 25, 14);

        jLabel3.setText("Prenom :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(76, 106, 43, 14);

        nom_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(nom_Field);
        nom_Field.setBounds(129, 61, 206, 20);
        getContentPane().add(prenom_Field);
        prenom_Field.setBounds(129, 103, 206, 20);

        valider_button.setText("Valider");
        valider_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valider_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(valider_button);
        valider_button.setBounds(270, 361, 65, 23);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Retour.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 361, 121, 37);

        Role_Field.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));
        getContentPane().add(Role_Field);
        Role_Field.setBounds(129, 141, 206, 20);

        jLabel4.setText("Role :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(91, 144, 28, 14);
        getContentPane().add(Email_Field);
        Email_Field.setBounds(129, 172, 206, 20);

        jLabel5.setText("E-mail :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(84, 175, 35, 14);
        getContentPane().add(Tel_Field);
        Tel_Field.setBounds(129, 203, 206, 20);

        jLabel6.setText("Telephone :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(62, 206, 57, 14);
        getContentPane().add(login_Field);
        login_Field.setBounds(129, 229, 206, 20);

        jLabel7.setText("Login :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(87, 232, 32, 14);
        getContentPane().add(Password_Field);
        Password_Field.setBounds(129, 255, 206, 20);

        jLabel8.setText("Passeword :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 258, 59, 14);

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifier);
        btnModifier.setBounds(189, 361, 71, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        //new Accueil().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (user!=null) {
            
            nom_Field.setText(user.getNom());
            prenom_Field.setText(user.getPrenom());
            Email_Field.setText(user.getMail());
            Tel_Field.setText(user.getTel());
            login_Field.setText(user.getUserName());
            Password_Field.setText(user.getPassword());
            valider_button.setVisible(false);
            btnModifier.setVisible(true);
        }else
        {
            valider_button.setVisible(true);
            btnModifier.setVisible(false);
        }
       
    }//GEN-LAST:event_formWindowOpened

    private void valider_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valider_buttonActionPerformed
        // TODO add your handling code here:
        
        Utilisateur utilisateur = new Utilisateur(nom_Field.getText(), prenom_Field.getText(),Role_Field.getSelectedItem().toString(),login_Field.getText(),Password_Field.getText(),Email_Field.getText(),Tel_Field.getText());
        UtilisateurDAO utilisateurDAO = new UtilisateurDAO();
        if(utilisateurDAO.addUtilisateur(utilisateur) != 0){
            JOptionPane.showMessageDialog(this, "Ajout effectué avec succès !");
        }
    }//GEN-LAST:event_valider_buttonActionPerformed

    private void nom_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_FieldActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        Utilisateur equipe = new Utilisateur(user.getId(), user.getNom(), user.getPrenom(), Role_Field.getSelectedItem().toString(), user.getMail(), user.getTel(), user.getUserName(), user.getPassword());
        UtilisateurDAO employeDAO = new UtilisateurDAO();
        if(employeDAO.updateUtilisateur(equipe)){
            JOptionPane.showMessageDialog(this, "Modification effectué avec succès !");
            this.setVisible(false);
            new AfficherUtilisateur().setVisible(true);
        }
    }//GEN-LAST:event_btnModifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterUtilisateur().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email_Field;
    private javax.swing.JTextField Password_Field;
    private javax.swing.JComboBox Role_Field;
    private javax.swing.JTextField Tel_Field;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField login_Field;
    private javax.swing.JTextField nom_Field;
    private javax.swing.JTextField prenom_Field;
    private javax.swing.JButton valider_button;
    // End of variables declaration//GEN-END:variables
}
