/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.presentation;

import edu.esprit.dao.EquipeDAO;

import edu.esprit.entite.Equipe;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Wael Mallek
 */
public class AjouterEquipe extends javax.swing.JFrame {
static Equipe e=null;
    
    /**
     * Creates new form AjouterEquipe
     */
    public AjouterEquipe() {
        initComponents();
    }
    public AjouterEquipe(Equipe e) {
        initComponents();
        this.e=e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom_Field = new javax.swing.JTextField();
        entraineur_Field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Flux_text = new javax.swing.JTextField();
        Modifiericon = new javax.swing.JLabel();
        validericon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 700));
        setPreferredSize(new java.awt.Dimension(1366, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 170, 50, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Entraineur:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(490, 230, 70, 14);
        getContentPane().add(nom_Field);
        nom_Field.setBounds(566, 160, 190, 30);
        getContentPane().add(entraineur_Field);
        entraineur_Field.setBounds(566, 220, 190, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Flux :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(490, 290, 50, 14);
        getContentPane().add(Flux_text);
        Flux_text.setBounds(566, 280, 190, 30);

        Modifiericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/modifier.png"))); // NOI18N
        Modifiericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifiericonMouseClicked(evt);
            }
        });
        getContentPane().add(Modifiericon);
        Modifiericon.setBounds(560, 410, 160, 50);

        validericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/valider.png"))); // NOI18N
        validericon.setText("jLabel11");
        validericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validericonMouseClicked(evt);
            }
        });
        getContentPane().add(validericon);
        validericon.setBounds(560, 410, 160, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouterequipe.png"))); // NOI18N
        jLabel1.setText("Ajouter une equipe :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1350, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (e!=null) {
            nom_Field.setText(e.getNom());
            entraineur_Field.setText(e.getEntraineur());
            Flux_text.setText(e.getFlux());
            validericon.setVisible(false);
            Modifiericon.setVisible(true);
        }else
        {
            validericon.setVisible(true);
            Modifiericon.setVisible(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void ModifiericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifiericonMouseClicked
        // TODO add your handling code here:
        Equipe equipe = new Equipe(e.getId(),nom_Field.getText(), entraineur_Field.getText(),Flux_text.getText());
        EquipeDAO employeDAO = new EquipeDAO();
        if(employeDAO.updateEquipe(equipe)){
            JOptionPane.showMessageDialog(this, "Modification effectué avec succès !");
            this.setVisible(false);
            new AfficherEquipe().setVisible(true);
        }
    }//GEN-LAST:event_ModifiericonMouseClicked

    private void validericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validericonMouseClicked
        // TODO add your handling code here:
        Equipe equipe = new Equipe(nom_Field.getText(), entraineur_Field.getText(),Flux_text.getText());
        EquipeDAO employeDAO = new EquipeDAO();
        if(employeDAO.addEquipe(equipe) != 0){
            JOptionPane.showMessageDialog(this, "Ajout effectué avec succès !");
            this.setVisible(false);
        }
    }//GEN-LAST:event_validericonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterEquipe().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Flux_text;
    private javax.swing.JLabel Modifiericon;
    private javax.swing.JTextField entraineur_Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nom_Field;
    private javax.swing.JLabel validericon;
    // End of variables declaration//GEN-END:variables
}
