/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.presentation;

import edu.esprit.dao.ButDAO;
import edu.esprit.dao.EquipeDAO;
import edu.esprit.dao.JoueurDAO;
import edu.esprit.dao.MatchDAO;
import edu.esprit.entite.But;
import edu.esprit.entite.Equipe;
import edu.esprit.entite.Joueur;
import edu.esprit.entite.Match;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerListModel;

/**
 *
 * @author Jaloul1
 */
public class AjouterResultat extends javax.swing.JFrame {

    /**
     * Creates new form AjouterResultat
     */
    EquipeDAO equipeDAO = new EquipeDAO();
    ArrayList<Equipe> equipes = equipeDAO.readAllEquipes();
    JoueurDAO joueurDAO = new JoueurDAO();
    ArrayList<Joueur> joueur = joueurDAO.readAllJoueurs();
    
    
    public AjouterResultat() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        validericon = new javax.swing.JLabel();
        Equipe1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        Equipe2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tem_but = new javax.swing.JTextField();
        Jouer_id = new javax.swing.JComboBox();
        Tem_but1 = new javax.swing.JTextField();
        Jouer_id1 = new javax.swing.JComboBox();
        Tem_but2 = new javax.swing.JTextField();
        Jouer_id2 = new javax.swing.JComboBox();
        Tem_but3 = new javax.swing.JTextField();
        Jouer_id3 = new javax.swing.JComboBox();
        Tem_but4 = new javax.swing.JTextField();
        Jouer_id4 = new javax.swing.JComboBox();
        Tem_but5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Jouer_id5 = new javax.swing.JComboBox();
        Tem_but6 = new javax.swing.JTextField();
        Jouer_id6 = new javax.swing.JComboBox();
        Tem_but7 = new javax.swing.JTextField();
        Jouer_id7 = new javax.swing.JComboBox();
        Tem_but8 = new javax.swing.JTextField();
        Jouer_id8 = new javax.swing.JComboBox();
        Tem_but9 = new javax.swing.JTextField();
        Jouer_id9 = new javax.swing.JComboBox();
        R1 = new javax.swing.JSpinner();
        R2 = new javax.swing.JSpinner();
        Retouricon1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 760));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        validericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/valider.png"))); // NOI18N
        validericon.setText("jLabel11");
        validericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validericonMouseClicked(evt);
            }
        });
        getContentPane().add(validericon);
        validericon.setBounds(630, 90, 160, 50);

        Equipe1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".:: Selectionner Equipe ::." }));
        Equipe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Equipe1ActionPerformed(evt);
            }
        });
        getContentPane().add(Equipe1);
        Equipe1.setBounds(480, 60, 149, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Equipe 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(381, 60, 70, 14);

        Equipe2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".:: Selectionner Equipe ::." }));
        Equipe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Equipe2ActionPerformed(evt);
            }
        });
        getContentPane().add(Equipe2);
        Equipe2.setBounds(800, 60, 149, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Equipe 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(960, 60, 70, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Joueur");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 200, 60, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Temp but");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(640, 200, 70, 14);

        Tem_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tem_butMouseExited(evt);
            }
        });
        Tem_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tem_butActionPerformed(evt);
            }
        });
        getContentPane().add(Tem_but);
        Tem_but.setBounds(620, 240, 81, 30);

        Jouer_id.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".:: Selectionner Jouer ::." }));
        getContentPane().add(Jouer_id);
        Jouer_id.setBounds(420, 250, 144, 20);

        Tem_but1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tem_but1MouseExited(evt);
            }
        });
        getContentPane().add(Tem_but1);
        Tem_but1.setBounds(620, 290, 81, 30);

        Jouer_id1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".:: Selectionner Jouer ::." }));
        getContentPane().add(Jouer_id1);
        Jouer_id1.setBounds(420, 290, 144, 20);

        Tem_but2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tem_but2MouseExited(evt);
            }
        });
        getContentPane().add(Tem_but2);
        Tem_but2.setBounds(620, 330, 81, 30);

        Jouer_id2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".:: Selectionner Jouer ::." }));
        getContentPane().add(Jouer_id2);
        Jouer_id2.setBounds(420, 340, 144, 20);

        Tem_but3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tem_but3MouseExited(evt);
            }
        });
        getContentPane().add(Tem_but3);
        Tem_but3.setBounds(620, 370, 81, 30);

        Jouer_id3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".:: Selectionner Jouer ::." }));
        getContentPane().add(Jouer_id3);
        Jouer_id3.setBounds(420, 380, 144, 20);

        Tem_but4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tem_but4MouseExited(evt);
            }
        });
        getContentPane().add(Tem_but4);
        Tem_but4.setBounds(620, 410, 81, 30);

        Jouer_id4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".:: Selectionner Jouer ::." }));
        getContentPane().add(Jouer_id4);
        Jouer_id4.setBounds(420, 420, 144, 20);

        Tem_but5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tem_but5MouseExited(evt);
            }
        });
        getContentPane().add(Tem_but5);
        Tem_but5.setBounds(920, 230, 81, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Joueur");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(770, 200, 50, 14);

        Jouer_id5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".:: Selectionner Jouer ::." }));
        getContentPane().add(Jouer_id5);
        Jouer_id5.setBounds(730, 240, 144, 20);

        Tem_but6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tem_but6MouseExited(evt);
            }
        });
        getContentPane().add(Tem_but6);
        Tem_but6.setBounds(920, 280, 81, 30);

        Jouer_id6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".:: Selectionner Jouer ::." }));
        getContentPane().add(Jouer_id6);
        Jouer_id6.setBounds(730, 290, 144, 20);

        Tem_but7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tem_but7MouseExited(evt);
            }
        });
        getContentPane().add(Tem_but7);
        Tem_but7.setBounds(920, 330, 81, 30);

        Jouer_id7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".:: Selectionner Jouer ::." }));
        getContentPane().add(Jouer_id7);
        Jouer_id7.setBounds(730, 340, 144, 20);

        Tem_but8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tem_but8MouseExited(evt);
            }
        });
        Tem_but8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tem_but8ActionPerformed(evt);
            }
        });
        getContentPane().add(Tem_but8);
        Tem_but8.setBounds(920, 370, 81, 30);

        Jouer_id8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".:: Selectionner Jouer ::." }));
        Jouer_id8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jouer_id8ActionPerformed(evt);
            }
        });
        getContentPane().add(Jouer_id8);
        Jouer_id8.setBounds(730, 380, 144, 20);

        Tem_but9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tem_but9MouseExited(evt);
            }
        });
        getContentPane().add(Tem_but9);
        Tem_but9.setBounds(920, 410, 81, 30);

        Jouer_id9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".:: Selectionner Jouer ::." }));
        getContentPane().add(Jouer_id9);
        Jouer_id9.setBounds(730, 420, 144, 20);

        R1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                R1StateChanged(evt);
            }
        });
        R1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                R1AncestorAdded(evt);
            }
        });
        getContentPane().add(R1);
        R1.setBounds(650, 60, 50, 30);

        R2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                R2StateChanged(evt);
            }
        });
        getContentPane().add(R2);
        R2.setBounds(719, 60, 50, 30);

        Retouricon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/precident.png"))); // NOI18N
        Retouricon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Retouricon1MouseClicked(evt);
            }
        });
        getContentPane().add(Retouricon1);
        Retouricon1.setBounds(10, 580, 160, 45);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Temp but");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(930, 200, 60, 14);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouterresultat.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(4, 0, 1350, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (int i = 0; i < equipes.size(); i++) {
            Equipe1.addItem(equipes.get(i).getNom());
            Equipe2.addItem(equipes.get(i).getNom());
           // Equipe1.set
            
            
        }
        for (int i = 0; i < joueur.size(); i++) {
            Jouer_id.addItem(joueur.get(i).getNom());
            Jouer_id1.addItem(joueur.get(i).getNom());
            Jouer_id2.addItem(joueur.get(i).getNom());
            Jouer_id3.addItem(joueur.get(i).getNom());
            Jouer_id4.addItem(joueur.get(i).getNom());
            Jouer_id5.addItem(joueur.get(i).getNom());
            Jouer_id6.addItem(joueur.get(i).getNom());
            Jouer_id7.addItem(joueur.get(i).getNom());
            Jouer_id8.addItem(joueur.get(i).getNom());
            Jouer_id9.addItem(joueur.get(i).getNom());
            
        }
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        
        Tem_but.setVisible(false);
        Jouer_id.setVisible(false);
        Tem_but1.setVisible(false);
        Jouer_id1.setVisible(false);
        Tem_but2.setVisible(false);
        Jouer_id2.setVisible(false);
        Tem_but3.setVisible(false);
        Jouer_id3.setVisible(false);
        Tem_but4.setVisible(false);
        Jouer_id4.setVisible(false);
        
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        Tem_but5.setVisible(false);
        Jouer_id5.setVisible(false); 
        Tem_but6.setVisible(false);
        Jouer_id6.setVisible(false);
        Tem_but7.setVisible(false);
        Jouer_id7.setVisible(false);
        Tem_but8.setVisible(false);
        Jouer_id8.setVisible(false);
        Tem_but9.setVisible(false);
        Jouer_id9.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void Tem_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tem_butActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tem_butActionPerformed

    private void Tem_but8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tem_but8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tem_but8ActionPerformed

    private void Tem_butMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tem_butMouseExited
        // TODO add your handling code here:
        if(Tem_but.getText().equals("")==false)
        {
            
        
        Joueur joueurs1=joueurDAO.readJoueurNom(Jouer_id.getSelectedItem().toString());
        But but=new But(1, joueurs1.getId(), Tem_but.getText());
        ButDAO butdao=new ButDAO();
        if(butdao.addBut(but) != 0){
        Tem_but.setVisible(false);
        Jouer_id.setVisible(false);
        }
        }
    }//GEN-LAST:event_Tem_butMouseExited

    private void Tem_but1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tem_but1MouseExited
        // TODO add your handling code here:
        if(Tem_but1.getText().equals("")==false)
        {Joueur joueurs2=joueurDAO.readJoueurNom(Jouer_id1.getSelectedItem().toString());
        But but=new But(1, joueurs2.getId(), Tem_but1.getText());
        ButDAO butdao=new ButDAO();
        if(butdao.addBut(but) != 0){
        Tem_but1.setVisible(false);
        Jouer_id1.setVisible(false);
        }}
    }//GEN-LAST:event_Tem_but1MouseExited

    private void Tem_but2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tem_but2MouseExited
        // TODO add your handling code here:
        if(Tem_but2.getText().equals("")==false)
        {
        Joueur joueurs2=joueurDAO.readJoueurNom(Jouer_id2.getSelectedItem().toString());
        But but=new But(1, joueurs2.getId(), Tem_but2.getText());
        ButDAO butdao=new ButDAO();
        if(butdao.addBut(but) != 0){
        Tem_but2.setVisible(false);
        Jouer_id2.setVisible(false);
        }}
    }//GEN-LAST:event_Tem_but2MouseExited

    private void Tem_but5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tem_but5MouseExited
        // TODO add your handling code here:
        if(Tem_but5.getText().equals("")==false)
        {
        Joueur joueurs2=joueurDAO.readJoueurNom(Jouer_id5.getSelectedItem().toString());
        But but=new But(1, joueurs2.getId(), Tem_but5.getText());
        ButDAO butdao=new ButDAO();
        if(butdao.addBut(but) != 0){
        Tem_but5.setVisible(false);
        Jouer_id5.setVisible(false);
        }}
    }//GEN-LAST:event_Tem_but5MouseExited

    private void Tem_but3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tem_but3MouseExited
        // TODO add your handling code here:
        if(Tem_but3.getText().equals("")==false)
        {
        Joueur joueurs2=joueurDAO.readJoueurNom(Jouer_id3.getSelectedItem().toString());
        But but=new But(1, joueurs2.getId(), Tem_but3.getText());
        ButDAO butdao=new ButDAO();
        if(butdao.addBut(but) != 0){Tem_but3.setVisible(false);
        Jouer_id3.setVisible(false);
        }
        }
    }//GEN-LAST:event_Tem_but3MouseExited

    private void Tem_but4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tem_but4MouseExited
        // TODO add your handling code here:
        if(Tem_but4.getText().equals("")==false)
        {
        Joueur joueurs2=joueurDAO.readJoueurNom(Jouer_id4.getSelectedItem().toString());
        But but=new But(1, joueurs2.getId(), Tem_but4.getText());
        ButDAO butdao=new ButDAO();
        if(butdao.addBut(but) != 0){ Tem_but4.setVisible(false);
        Jouer_id4.setVisible(false);
        }
       }
    }//GEN-LAST:event_Tem_but4MouseExited

    private void Tem_but6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tem_but6MouseExited
        // TODO add your handling code here:
        if(Tem_but6.getText().equals("")==false)
        {
        Joueur joueurs2=joueurDAO.readJoueurNom(Jouer_id6.getSelectedItem().toString());
        But but=new But(1, joueurs2.getId(), Tem_but6.getText());
        ButDAO butdao=new ButDAO();
        if(butdao.addBut(but) != 0){Tem_but6.setVisible(false);
        Jouer_id6.setVisible(false);
        }
        }
    }//GEN-LAST:event_Tem_but6MouseExited

    private void Tem_but7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tem_but7MouseExited
        // TODO add your handling code here:
        if(Tem_but7.getText().equals("")==false)
        {
        Joueur joueurs2=joueurDAO.readJoueurNom(Jouer_id7.getSelectedItem().toString());
        But but=new But(1, joueurs2.getId(), Tem_but7.getText());
        ButDAO butdao=new ButDAO();
        if(butdao.addBut(but) != 0){Tem_but7.setVisible(false);
        Jouer_id7.setVisible(false);
        }
        }
    }//GEN-LAST:event_Tem_but7MouseExited

    private void Tem_but8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tem_but8MouseExited
        // TODO add your handling code here:
        if(Tem_but8.getText().equals("")==false)
        {
        Joueur joueurs2=joueurDAO.readJoueurNom(Jouer_id8.getSelectedItem().toString());
        But but=new But(1, joueurs2.getId(), Tem_but8.getText());
        ButDAO butdao=new ButDAO();
        if(butdao.addBut(but) != 0){
           Tem_but8.setVisible(false);
        Jouer_id8.setVisible(false);
        }
        }
    }//GEN-LAST:event_Tem_but8MouseExited

    private void Tem_but9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tem_but9MouseExited
        // TODO add your handling code here:
        if(Tem_but9.getText().equals("")==false)
        {
        Joueur joueurs2=joueurDAO.readJoueurNom(Jouer_id9.getSelectedItem().toString());
        But but=new But(1, joueurs2.getId(), Tem_but9.getText());
        ButDAO butdao=new ButDAO();
        if(butdao.addBut(but) != 0){
            Tem_but9.setVisible(false);
        Jouer_id9.setVisible(false);  }
        }
    }//GEN-LAST:event_Tem_but9MouseExited

    private void validericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validericonMouseClicked
        // TODO add your handling code here:
        Equipe equipe = equipeDAO.readEquipeNom(Equipe1.getSelectedItem().toString()); //Récuperer l'equipe séléctionnée à partir du ComboBox 
        Equipe equipe2 = equipeDAO.readEquipeNom(Equipe2.getSelectedItem().toString()); 
        Match match;
        match = new Match(equipe.getId(), Integer.parseInt(R1.getValue().toString()), Integer.parseInt(R2.getValue().toString()), equipe2.getId());
        
        MatchDAO employeDAO = new MatchDAO();
        if(employeDAO.addMatch(match) != 0){
            JOptionPane.showMessageDialog(this, "Ajout effectué avec succès !");
            R1.setEnabled(false);
            R2.setEnabled(false);
        }
        
        
        
        Joueur joueurs3=joueurDAO.readJoueurNom(Jouer_id2.getSelectedItem().toString());
        Joueur joueurs4=joueurDAO.readJoueurNom(Jouer_id3.getSelectedItem().toString());
        Joueur joueurs5=joueurDAO.readJoueurNom(Jouer_id4.getSelectedItem().toString());
        
        
    }//GEN-LAST:event_validericonMouseClicked

    private void R1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_R1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_R1AncestorAdded

    private void R1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_R1StateChanged
        // TODO add your handling code here:
        int nb=0;
        
        nb=Integer.parseInt(R1.getValue().toString());
        if(nb==0)
        {
            jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        
        Tem_but.setVisible(false);
        Jouer_id.setVisible(false);
        Tem_but1.setVisible(false);
        Jouer_id1.setVisible(false);
        Tem_but2.setVisible(false);
        Jouer_id2.setVisible(false);
        Tem_but3.setVisible(false);
        Jouer_id3.setVisible(false);
        Tem_but4.setVisible(false);
        Jouer_id4.setVisible(false);
        }
        if(nb==1)
        {
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        Tem_but.setVisible(true);
        Jouer_id.setVisible(true); 
        Tem_but1.setVisible(false);
        Jouer_id1.setVisible(false);
        Tem_but2.setVisible(false);
        Jouer_id2.setVisible(false);
        Tem_but3.setVisible(false);
        Jouer_id3.setVisible(false);
        Tem_but4.setVisible(false);
        Jouer_id4.setVisible(false);
        }
        if(nb==2)
        {
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        Tem_but.setVisible(true);
        Jouer_id.setVisible(true);
        Tem_but1.setVisible(true);
        Jouer_id1.setVisible(true);
        Tem_but2.setVisible(false);
        Jouer_id2.setVisible(false);
        Tem_but3.setVisible(false);
        Jouer_id3.setVisible(false);
        Tem_but4.setVisible(false);
        Jouer_id4.setVisible(false);
        }
        if(nb==3)
        {
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        Tem_but.setVisible(true);
        Jouer_id.setVisible(true);
        Tem_but1.setVisible(true);
        Jouer_id1.setVisible(true);
        Tem_but2.setVisible(true);
        Jouer_id2.setVisible(true);
        Tem_but3.setVisible(false);
        Jouer_id3.setVisible(false);
        Tem_but4.setVisible(false);
        Jouer_id4.setVisible(false);
        }
        if(nb==4)
        {
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        Tem_but.setVisible(true);
        Jouer_id.setVisible(true);
        Tem_but1.setVisible(true);
        Jouer_id1.setVisible(true);
        Tem_but2.setVisible(true);
        Jouer_id2.setVisible(true);
        Tem_but3.setVisible(true);
        Jouer_id3.setVisible(true);
        Tem_but4.setVisible(false);
        Jouer_id4.setVisible(false);
        }
        if(nb==5)
        {
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        Tem_but.setVisible(true);
        Jouer_id.setVisible(true);
        Tem_but1.setVisible(true);
        Jouer_id1.setVisible(true);
        Tem_but2.setVisible(true);
        Jouer_id2.setVisible(true);
        Tem_but3.setVisible(true);
        Jouer_id3.setVisible(true);
        Tem_but4.setVisible(true);
        Jouer_id4.setVisible(true);
        }
    }//GEN-LAST:event_R1StateChanged

    private void R2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_R2StateChanged
        // TODO add your handling code here:
           int nb=0;
        
        nb=Integer.parseInt(R2.getValue().toString());
        if(nb==0)
        {
            jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        Tem_but5.setVisible(false);
        Jouer_id5.setVisible(false); 
        Tem_but6.setVisible(false);
        Jouer_id6.setVisible(false);
        Tem_but7.setVisible(false);
        Jouer_id7.setVisible(false);
        Tem_but8.setVisible(false);
        Jouer_id8.setVisible(false);
        Tem_but9.setVisible(false);
        Jouer_id9.setVisible(false);
        }
        if(nb==1)
        {
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        Tem_but5.setVisible(true);
        Jouer_id5.setVisible(true); 
        Tem_but6.setVisible(false);
        Jouer_id6.setVisible(false);
        Tem_but7.setVisible(false);
        Jouer_id7.setVisible(false);
        Tem_but8.setVisible(false);
        Jouer_id8.setVisible(false);
        Tem_but9.setVisible(false);
        Jouer_id9.setVisible(false);
        }
        if(nb==2)
        {
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        Tem_but5.setVisible(true);
        Jouer_id5.setVisible(true); 
        Tem_but6.setVisible(true);
        Jouer_id6.setVisible(true);
        Tem_but7.setVisible(false);
        Jouer_id7.setVisible(false);
        Tem_but8.setVisible(false);
        Jouer_id8.setVisible(false);
        Tem_but9.setVisible(false);
        Jouer_id9.setVisible(false);
        }
        if(nb==3)
        {
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        Tem_but5.setVisible(true);
        Jouer_id5.setVisible(true); 
        Tem_but6.setVisible(true);
        Jouer_id6.setVisible(true);
        Tem_but7.setVisible(true);
        Jouer_id7.setVisible(true);
        Tem_but8.setVisible(false);
        Jouer_id8.setVisible(false);
        Tem_but9.setVisible(false);
        Jouer_id9.setVisible(false);
        }
        if(nb==4)
        {
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        Tem_but5.setVisible(true);
        Jouer_id5.setVisible(true); 
        Tem_but6.setVisible(true);
        Jouer_id6.setVisible(true);
        Tem_but7.setVisible(true);
        Jouer_id7.setVisible(true);
        Tem_but8.setVisible(true);
        Jouer_id8.setVisible(true);
        Tem_but9.setVisible(false);
        Jouer_id9.setVisible(false);
        }
        if(nb==5)
        {
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        Tem_but5.setVisible(true);
        Jouer_id5.setVisible(true); 
        Tem_but6.setVisible(true);
        Jouer_id6.setVisible(true);
        Tem_but7.setVisible(true);
        Jouer_id7.setVisible(true);
        Tem_but8.setVisible(true);
        Jouer_id8.setVisible(true);
        Tem_but9.setVisible(true);
        Jouer_id9.setVisible(true);
        }
    }//GEN-LAST:event_R2StateChanged

    private void Retouricon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Retouricon1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Retouricon1MouseClicked

    private void Jouer_id8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jouer_id8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jouer_id8ActionPerformed

    private void Equipe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Equipe1ActionPerformed
        // TODO add your handling code here:
        Equipe equipe = equipeDAO.readEquipeNom(Equipe1.getSelectedItem().toString()); 
        ArrayList<Joueur> joueur1 = joueurDAO.readAllJoueursParEquipe(equipe.getId());
        Jouer_id.removeAllItems();
        Jouer_id1.removeAllItems();
        Jouer_id2.removeAllItems();
        Jouer_id3.removeAllItems();
        Jouer_id4.removeAllItems();
        
        for (int i = 0; i < joueur1.size(); i++) {
            Jouer_id.addItem(joueur1.get(i).getNom());
            Jouer_id1.addItem(joueur1.get(i).getNom());
            Jouer_id2.addItem(joueur1.get(i).getNom());
            Jouer_id3.addItem(joueur1.get(i).getNom());
            Jouer_id4.addItem(joueur1.get(i).getNom());
            
            
        }
    }//GEN-LAST:event_Equipe1ActionPerformed

    private void Equipe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Equipe2ActionPerformed
        // TODO add your handling code here:
         Equipe equipe = equipeDAO.readEquipeNom(Equipe1.getSelectedItem().toString()); 
        ArrayList<Joueur> joueur1 = joueurDAO.readAllJoueursParEquipe(equipe.getId());
        Jouer_id5.removeAllItems();
        Jouer_id6.removeAllItems();
        Jouer_id7.removeAllItems();
        Jouer_id8.removeAllItems();
        Jouer_id9.removeAllItems();
        
        for (int i = 0; i < joueur1.size(); i++) {
            Jouer_id5.addItem(joueur.get(i).getNom());
            Jouer_id6.addItem(joueur.get(i).getNom());
            Jouer_id7.addItem(joueur.get(i).getNom());
            Jouer_id8.addItem(joueur.get(i).getNom());
            Jouer_id9.addItem(joueur.get(i).getNom());
            
            
        }
    }//GEN-LAST:event_Equipe2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterResultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterResultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterResultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterResultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterResultat().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Equipe1;
    private javax.swing.JComboBox Equipe2;
    private javax.swing.JComboBox Jouer_id;
    private javax.swing.JComboBox Jouer_id1;
    private javax.swing.JComboBox Jouer_id2;
    private javax.swing.JComboBox Jouer_id3;
    private javax.swing.JComboBox Jouer_id4;
    private javax.swing.JComboBox Jouer_id5;
    private javax.swing.JComboBox Jouer_id6;
    private javax.swing.JComboBox Jouer_id7;
    private javax.swing.JComboBox Jouer_id8;
    private javax.swing.JComboBox Jouer_id9;
    private javax.swing.JSpinner R1;
    private javax.swing.JSpinner R2;
    private javax.swing.JLabel Retouricon1;
    private javax.swing.JTextField Tem_but;
    private javax.swing.JTextField Tem_but1;
    private javax.swing.JTextField Tem_but2;
    private javax.swing.JTextField Tem_but3;
    private javax.swing.JTextField Tem_but4;
    private javax.swing.JTextField Tem_but5;
    private javax.swing.JTextField Tem_but6;
    private javax.swing.JTextField Tem_but7;
    private javax.swing.JTextField Tem_but8;
    private javax.swing.JTextField Tem_but9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel validericon;
    // End of variables declaration//GEN-END:variables
}
