/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.presentation;

import api.RSSReader;
import edu.esprit.dao.EquipeDAO;
import edu.esprit.dao.FavoritsDAO;
import edu.esprit.dao.MatchDAO;
import edu.esprit.entite.Equipe;
import edu.esprit.entite.Favorits;
import edu.esprit.entite.Match;
import edu.esprit.entite.Utilisateur;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;

/**
 *
 * @author slimkhan
 */
public class DashboardUser extends javax.swing.JFrame {

    static Utilisateur u = null;
    
    /**
     * Creates new form DashboardUser
     */
    public DashboardUser() {
        initComponents();
        
        RSSReader reader = new RSSReader();
        news.setText(reader.parse("http://www.clubafricain.com/rss.asp"));
        Icon i=new ImageIcon("src/image/1.png");
        Eq1.setIcon(i);
    }
    public DashboardUser(Utilisateur u) {
        initComponents();
        this.u = u;
        user.setText(u.getPrenom()+" "+u.getNom());
        
        Favorits f = new Favorits();
        Equipe e,e1,e2 = new Equipe();
        Match m = new Match();
        FavoritsDAO fv = new FavoritsDAO();
        f = fv.readFavoritsID(u.getId());
        EquipeDAO eq = new EquipeDAO();
        e = eq.readEquipeID(f.getId_equipe());
        MatchDAO md = new MatchDAO();
        m = md.readLatsMatch(f.getId_equipe());
        
        RSSReader reader = new RSSReader();
        news.setText(reader.parse(e.getFlux()));
        //reader.parse1("http://www.clubafricain.com/rss.asp");
        
        
        if (m.getId_E1()==f.getId_equipe()) {
            e1= eq.readEquipeID(m.getId_E1());
            e2 = eq.readEquipeID(m.getId_E2());
        } else {
            e2= eq.readEquipeID(m.getId_E1());
            e1 = eq.readEquipeID(m.getId_E2());
        }
        
        
       
        
        
        Icon i=new ImageIcon("src/image/"+e1.getId()+".png");
        Icon i2=new ImageIcon("src/image/"+e2.getId()+".png");
        Eq1.setIcon(i);
        Eq2.setIcon(i2);
        
        R1.setText(e1.getNom()+"  :  "+m.getR1());
        R2.setText(+m.getR2()+" :   "+e2.getNom());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        play = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Eq2 = new javax.swing.JLabel();
        Eq1 = new javax.swing.JLabel();
        R1 = new javax.swing.JLabel();
        R2 = new javax.swing.JLabel();
        R = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        news = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1350, 690));
        setMinimumSize(new java.awt.Dimension(1350, 700));
        getContentPane().setLayout(null);

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/play.png"))); // NOI18N
        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playMouseClicked(evt);
            }
        });
        getContentPane().add(play);
        play.setBounds(920, 150, 70, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/equipicon.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 20, 90, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/favorit.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 20, 60, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profilicon.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 20, 70, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 10, 1160, 78);
        getContentPane().add(Eq2);
        Eq2.setBounds(550, 250, 100, 50);

        Eq1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1.png"))); // NOI18N
        getContentPane().add(Eq1);
        Eq1.setBounds(150, 250, 60, 50);

        R1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        R1.setForeground(new java.awt.Color(255, 255, 255));
        R1.setText("1");
        getContentPane().add(R1);
        R1.setBounds(240, 260, 120, 40);

        R2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        R2.setForeground(new java.awt.Color(255, 255, 255));
        R2.setText("3");
        getContentPane().add(R2);
        R2.setBounds(400, 260, 120, 40);

        R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rest.png"))); // NOI18N
        R.setText("jLabel3");
        getContentPane().add(R);
        R.setBounds(130, 230, 540, 90);

        user.setText("Nom Prenom");
        getContentPane().add(user);
        user.setBounds(1050, 180, 190, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile/nom.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1010, 170, 160, 41);

        news.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(news);
        news.setBounds(100, 400, 610, 240);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/news.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 380, 650, 280);

        fond.setForeground(new java.awt.Color(255, 255, 255));
        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fond2.png"))); // NOI18N
        fond.setMaximumSize(new java.awt.Dimension(1200, 773));
        fond.setMinimumSize(new java.awt.Dimension(1200, 773));
        getContentPane().add(fond);
        fond.setBounds(0, 0, 1350, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_playMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Favorits f = new Favorits();
        Equipe e = new Equipe();
        FavoritsDAO fv = new FavoritsDAO();
        f = fv.readFavoritsID(u.getId());
        new tachkila(f.getId_equipe()).setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Favorits f=new Favorits(0,u.getId(), 0);
        new AjouterFavorits(f).setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardUser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eq1;
    private javax.swing.JLabel Eq2;
    private javax.swing.JLabel R;
    private javax.swing.JLabel R1;
    private javax.swing.JLabel R2;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel news;
    private javax.swing.JLabel play;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
