/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.presentation;

import api.RSSReader;
import edu.esprit.dao.EquipeDAO;
import edu.esprit.dao.FavoritsDAO;
import edu.esprit.entite.Equipe;
import edu.esprit.entite.Favorits;
import edu.esprit.entite.Utilisateur;
import javax.swing.JEditorPane;

/**
 *
 * @author slimkhan
 */
public class DashboardUser extends javax.swing.JFrame {

    static Utilisateur u = null;
    /**
     * Creates new form DashboardUser
     */
    public DashboardUser() {
        initComponents();
        
        RSSReader reader = new RSSReader();
        news.setText(reader.parse("http://www.e-s-tunis.com/EST/misc/flux/rss.php"));
    }
    public DashboardUser(Utilisateur u) {
        initComponents();
        this.u = u;
        user.setText(u.getPrenom()+" "+u.getNom());
        
        Favorits f = new Favorits();
        Equipe e = new Equipe();
        FavoritsDAO fv = new FavoritsDAO();
        f = fv.readFavoritsID(u.getId());
        EquipeDAO eq = new EquipeDAO();
        e = eq.readEquipeID(f.getId_equipe());
        
        RSSReader reader = new RSSReader();
        news.setText(reader.parse(e.getFlux()));
        //reader.parse1("http://www.clubafricain.com/rss.asp");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        news = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultat = new javax.swing.JTextArea();
        user = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(892, 504));
        getContentPane().setLayout(null);

        news.setColumns(20);
        news.setRows(5);
        jScrollPane1.setViewportView(news);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 220, 488, 205);

        resultat.setColumns(20);
        resultat.setRows(5);
        jScrollPane2.setViewportView(resultat);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(19, 67, 488, 90);

        user.setText("Nom Prenom");
        getContentPane().add(user);
        user.setBounds(530, 10, 190, 20);

        jButton1.setText("Ajouter favories");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 70, 160, 29);

        jButton2.setText("Afficher les équipes");
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 110, 160, 29);

        jButton3.setText("toutes les résultats");
        getContentPane().add(jButton3);
        jButton3.setBounds(360, 160, 150, 29);

        jButton4.setText("Voir les joueurs ");
        getContentPane().add(jButton4);
        jButton4.setBounds(550, 150, 160, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Favorits fav=new Favorits(0, u.getId(),0);
        new AjouterFavorits(fav).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardUser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea news;
    private javax.swing.JTextArea resultat;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
