/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.presentation;
import edu.esprit.presentation.AfficherEquipe;

/**
 *
 * @author Jaloul1
 */
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utilisqteur = new javax.swing.JLabel();
        AffiEquip = new javax.swing.JLabel();
        AffichFavorit = new javax.swing.JLabel();
        listeJoueur = new javax.swing.JLabel();
        addequip = new javax.swing.JLabel();
        addfavorit = new javax.swing.JLabel();
        addjoueur = new javax.swing.JLabel();
        adduser = new javax.swing.JLabel();
        addmatch = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 700));
        getContentPane().setLayout(null);

        utilisqteur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/UTILISATEUR.png"))); // NOI18N
        utilisqteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utilisqteurMouseClicked(evt);
            }
        });
        getContentPane().add(utilisqteur);
        utilisqteur.setBounds(380, 390, 180, 45);

        AffiEquip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/LISTEEQUIPE.png"))); // NOI18N
        AffiEquip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AffiEquipMouseClicked(evt);
            }
        });
        getContentPane().add(AffiEquip);
        AffiEquip.setBounds(380, 180, 158, 50);

        AffichFavorit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/LISTEFAVORIT.png"))); // NOI18N
        AffichFavorit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AffichFavoritMouseClicked(evt);
            }
        });
        getContentPane().add(AffichFavorit);
        AffichFavorit.setBounds(380, 250, 170, 45);

        listeJoueur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/LISTEJOUEURS.png"))); // NOI18N
        listeJoueur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeJoueurMouseClicked(evt);
            }
        });
        getContentPane().add(listeJoueur);
        listeJoueur.setBounds(380, 320, 170, 50);

        addequip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/ADDEQUIP.png"))); // NOI18N
        addequip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addequipMouseClicked(evt);
            }
        });
        getContentPane().add(addequip);
        addequip.setBounds(820, 180, 158, 50);

        addfavorit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/ADDFAVORIT.png"))); // NOI18N
        addfavorit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addfavoritMouseClicked(evt);
            }
        });
        getContentPane().add(addfavorit);
        addfavorit.setBounds(820, 250, 170, 44);

        addjoueur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/ADDJOUEUR.png"))); // NOI18N
        addjoueur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addjoueurMouseClicked(evt);
            }
        });
        getContentPane().add(addjoueur);
        addjoueur.setBounds(820, 320, 170, 50);

        adduser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/ADDUSER.png"))); // NOI18N
        adduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adduserMouseClicked(evt);
            }
        });
        getContentPane().add(adduser);
        adduser.setBounds(820, 400, 180, 45);

        addmatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/ADDMATCH.png"))); // NOI18N
        addmatch.setText("jLabel3");
        getContentPane().add(addmatch);
        addmatch.setBounds(600, 460, 160, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/ADMIN.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1350, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AffiEquipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AffiEquipMouseClicked
        // TODO add your handling code here:
      new AfficherEquipe().setVisible(true);
    }//GEN-LAST:event_AffiEquipMouseClicked

    private void AffichFavoritMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AffichFavoritMouseClicked
        // TODO add your handling code here:
        new AfficherFavorits().setVisible(true);
    }//GEN-LAST:event_AffichFavoritMouseClicked

    private void listeJoueurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeJoueurMouseClicked
        // TODO add your handling code here:
        new AfficherJoueur().setVisible(true);
    }//GEN-LAST:event_listeJoueurMouseClicked

    private void utilisqteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilisqteurMouseClicked
        // TODO add your handling code here:
        new AfficherUtilisateur().setVisible(true);
    }//GEN-LAST:event_utilisqteurMouseClicked

    private void addequipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addequipMouseClicked
        // TODO add your handling code here:
        new AjouterEquipe().setVisible(true);
    }//GEN-LAST:event_addequipMouseClicked

    private void addfavoritMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfavoritMouseClicked
        // TODO add your handling code here:
         new AjouterFavorits().setVisible(true);
    }//GEN-LAST:event_addfavoritMouseClicked

    private void addjoueurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addjoueurMouseClicked
        // TODO add your handling code here:
         new AjouterJoueur().setVisible(true);
    }//GEN-LAST:event_addjoueurMouseClicked

    private void adduserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adduserMouseClicked
        // TODO add your handling code here:
         new AjouterUtilisateur().setVisible(true);
    }//GEN-LAST:event_adduserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AffiEquip;
    private javax.swing.JLabel AffichFavorit;
    private javax.swing.JLabel addequip;
    private javax.swing.JLabel addfavorit;
    private javax.swing.JLabel addjoueur;
    private javax.swing.JLabel addmatch;
    private javax.swing.JLabel adduser;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel listeJoueur;
    private javax.swing.JLabel utilisqteur;
    // End of variables declaration//GEN-END:variables
}
