/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.presentation;


import edu.esprit.dao.UtilisateurDAO;
import edu.esprit.entite.Utilisateur;
import static edu.esprit.presentation.AjouterEquipe.e;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Wael Mallek
 */
public class EnregistrerUser extends javax.swing.JFrame {
 static Utilisateur user=null;
    
    /**
     * Creates new form AjouterUtilisateur
     */
    public EnregistrerUser() {
        initComponents();
    }

    EnregistrerUser(Utilisateur e) {
        initComponents();
        user=e;
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom_Field = new javax.swing.JTextField();
        prenom_Field = new javax.swing.JTextField();
        Email_Field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tel_Field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        login_Field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Password_Field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        validericon = new javax.swing.JLabel();
        Retouricon = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Nom:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 120, 50, 14);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Prenom :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 160, 80, 14);

        nom_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(nom_Field);
        nom_Field.setBounds(586, 110, 170, 30);
        getContentPane().add(prenom_Field);
        prenom_Field.setBounds(586, 150, 170, 30);
        getContentPane().add(Email_Field);
        Email_Field.setBounds(586, 190, 170, 30);

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("E-mail :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(510, 200, 60, 14);
        getContentPane().add(Tel_Field);
        Tel_Field.setBounds(586, 230, 170, 30);

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Telephone :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 240, 90, 14);
        getContentPane().add(login_Field);
        login_Field.setBounds(586, 270, 170, 30);

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Login :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 280, 50, 14);
        getContentPane().add(Password_Field);
        Password_Field.setBounds(586, 310, 170, 30);

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Passeword :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(490, 320, 90, 14);

        validericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/valider.png"))); // NOI18N
        validericon.setText("jLabel11");
        validericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validericonMouseClicked(evt);
            }
        });
        getContentPane().add(validericon);
        validericon.setBounds(560, 410, 160, 50);

        Retouricon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nav/precident.png"))); // NOI18N
        Retouricon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetouriconMouseClicked(evt);
            }
        });
        getContentPane().add(Retouricon);
        Retouricon.setBounds(50, 580, 160, 45);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouterutilisateur.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1370, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (user!=null) {
            
            nom_Field.setText(user.getNom());
            prenom_Field.setText(user.getPrenom());
            Email_Field.setText(user.getMail());
            Tel_Field.setText(user.getTel());
            login_Field.setText(user.getUserName());
            Password_Field.setText(user.getPassword());
            validericon.setVisible(false);
           
        }else
        {
            validericon.setVisible(true);
          
        }
       
    }//GEN-LAST:event_formWindowOpened

    private void nom_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_FieldActionPerformed

    private void validericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validericonMouseClicked
        // TODO add your handling code here:
        if (nom_Field.getText().equals("")&&login_Field.getText().equals("")&&Password_Field.getText().equals("")&&Email_Field.getText().equals("")&&Tel_Field.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP Remplire tous les champs de saisir!!!!");
        }else{
         Utilisateur utilisateur = new Utilisateur(nom_Field.getText(), prenom_Field.getText(),"User",login_Field.getText(),Password_Field.getText(),Email_Field.getText(),Tel_Field.getText());
        UtilisateurDAO utilisateurDAO = new UtilisateurDAO();
        if(utilisateurDAO.addUtilisateur(utilisateur) != 0){
            JOptionPane.showMessageDialog(this, "Ajout effectué avec succès !");
            this.setVisible(false);
        }}
    }//GEN-LAST:event_validericonMouseClicked

    private void RetouriconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetouriconMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_RetouriconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnregistrerUser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email_Field;
    private javax.swing.JTextField Password_Field;
    private javax.swing.JLabel Retouricon;
    private javax.swing.JTextField Tel_Field;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField login_Field;
    private javax.swing.JTextField nom_Field;
    private javax.swing.JTextField prenom_Field;
    private javax.swing.JLabel validericon;
    // End of variables declaration//GEN-END:variables
}
