/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.presentation;

import edu.esprit.dao.JoueurDAO;
import edu.esprit.entite.Joueur;
import java.util.ArrayList;

/**
 *
 * @author Jaloul1
 */
public class tachkila extends javax.swing.JFrame {

    /**
     * Creates new form tachkila
     */
    public tachkila() {
        initComponents();
        
    }

    tachkila(int id_equipe) {
        initComponents();
        ArrayList<Joueur> equipe;
    JoueurDAO eDAO = new JoueurDAO();
        System.out.println(id_equipe);
    equipe=eDAO.readAllJoueursParEquipe(id_equipe);
    if(id_equipe==2)
    {
    Nj1.setText(equipe.get(0).getPrenom()); 
    Nj2.setText(equipe.get(1).getPrenom());
    Nj3.setText(equipe.get(2).getPrenom()); 
    Nj4.setText(equipe.get(3).getPrenom());
    Nj5.setText(equipe.get(4).getPrenom()); 
    Nj6.setText(equipe.get(5).getPrenom());
    Nj7.setText(equipe.get(6).getPrenom()); 
    Nj8.setText(equipe.get(7).getPrenom());
    Nj9.setText(equipe.get(8).getPrenom());
    Nj11.setText(equipe.get(9).getPrenom()); 
    Nj12.setText(equipe.get(10).getPrenom());
    }
    else
        if(id_equipe==1)
        {
            Nj1.setText(equipe.get(0).getPrenom()); 
    Nj2.setText(equipe.get(1).getPrenom());
    Nj3.setText(equipe.get(2).getPrenom()); 
    Nj4.setText(equipe.get(3).getPrenom());
    Nj5.setText(equipe.get(4).getPrenom()); 
    nj26.setText(equipe.get(5).getPrenom());
    Nj7.setText(equipe.get(6).getPrenom()); 
    Nj8.setText(equipe.get(7).getPrenom());
    nj29.setText(equipe.get(8).getPrenom());
    Nj11.setText(equipe.get(9).getPrenom()); 
    Nj12.setText(equipe.get(10).getPrenom());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nj1 = new javax.swing.JLabel();
        Nj2 = new javax.swing.JLabel();
        Nj3 = new javax.swing.JLabel();
        Nj4 = new javax.swing.JLabel();
        Nj5 = new javax.swing.JLabel();
        Nj7 = new javax.swing.JLabel();
        Nj8 = new javax.swing.JLabel();
        Nj11 = new javax.swing.JLabel();
        Nj12 = new javax.swing.JLabel();
        Nj6 = new javax.swing.JLabel();
        Nj9 = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();
        nj26 = new javax.swing.JLabel();
        nj29 = new javax.swing.JLabel();
        fond1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(674, 835));
        setMinimumSize(new java.awt.Dimension(674, 835));
        getContentPane().setLayout(null);

        Nj1.setText("jLabel3");
        getContentPane().add(Nj1);
        Nj1.setBounds(320, 120, 45, 16);

        Nj2.setText("jLabel2");
        getContentPane().add(Nj2);
        Nj2.setBounds(60, 280, 45, 16);

        Nj3.setText("jLabel3");
        getContentPane().add(Nj3);
        Nj3.setBounds(200, 280, 45, 16);

        Nj4.setText("jLabel3");
        getContentPane().add(Nj4);
        Nj4.setBounds(380, 280, 45, 16);

        Nj5.setText("jLabel3");
        getContentPane().add(Nj5);
        Nj5.setBounds(550, 280, 45, 16);

        Nj7.setText("jLabel3");
        getContentPane().add(Nj7);
        Nj7.setBounds(230, 480, 45, 16);

        Nj8.setText("jLabel3");
        getContentPane().add(Nj8);
        Nj8.setBounds(440, 480, 45, 16);

        Nj11.setText("jLabel3");
        getContentPane().add(Nj11);
        Nj11.setBounds(190, 740, 45, 16);

        Nj12.setText("jLabel3");
        getContentPane().add(Nj12);
        Nj12.setBounds(440, 740, 45, 16);

        Nj6.setText("jLabel3");
        getContentPane().add(Nj6);
        Nj6.setBounds(60, 580, 45, 16);

        Nj9.setText("jLabel3");
        getContentPane().add(Nj9);
        Nj9.setBounds(590, 580, 45, 16);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/442.png"))); // NOI18N
        fond.setText("jLabel1");
        getContentPane().add(fond);
        fond.setBounds(0, 0, 670, 830);

        nj26.setText("jLabel1");
        getContentPane().add(nj26);
        nj26.setBounds(60, 490, 45, 16);

        nj29.setText("jLabel1");
        getContentPane().add(nj29);
        nj29.setBounds(590, 480, 45, 16);

        fond1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/4411.png"))); // NOI18N
        fond1.setText("jLabel1");
        getContentPane().add(fond1);
        fond1.setBounds(0, 0, 670, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tachkila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tachkila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tachkila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tachkila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tachkila().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nj1;
    private javax.swing.JLabel Nj11;
    private javax.swing.JLabel Nj12;
    private javax.swing.JLabel Nj2;
    private javax.swing.JLabel Nj3;
    private javax.swing.JLabel Nj4;
    private javax.swing.JLabel Nj5;
    private javax.swing.JLabel Nj6;
    private javax.swing.JLabel Nj7;
    private javax.swing.JLabel Nj8;
    private javax.swing.JLabel Nj9;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel fond1;
    private javax.swing.JLabel nj26;
    private javax.swing.JLabel nj29;
    // End of variables declaration//GEN-END:variables
}
